# -*- coding: utf-8 -*-
"""Cartogram

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qX2HN2TqskwZ9oz2Z9aIEctwUyHHos3c
"""

# Create a Statue of Liberty (coordinates 40.6892, -74.0445) map and add a marker for the same on the map.
import folium
liberty_map = folium.Map(location=[40.6892, -74.0445], width='90%', height='70%', zoom_start=17)
folium.Marker(location=[40.6892, -74.0445], popup='Statue of Liberty').add_to(liberty_map)
liberty_map

"""In the above program we have imported the map using `folium` module.

First, we have passed the coordinates in the `location` parameter. Then we have set the width and height of the map as (90 X 70) by passing the values in `width` and `height` parameters.

We have set the initial zoom value as `17` in the `zoom_start` parameter inside the `folium.Map()` function, to get a closer view of the location in the map.

We used the `add_to()` function whose input is the map in which we want to add the marker.

We have used the parameter called `popup` inside the `folium.Marker()` function to popup the information **Statue of Liberty** on the marker when a user clicks on it.

---

#### Activity 2: Mark the **Marina Beach** with circular marker

Given the coordinates (13.0556, 80.2837) of **Marina Beach** which is the 2nd largest beach in the world located in Chennai. Mark the location with a circular marker and also add a pop-up of the location on the Folium map.
"""

# Create a Chennai map (coordinates 13.0556, 80.2837) and add a circular marker for the Marina Beach on the map.
chennai_map = folium.Map(location=[13.0556, 80.2837], width='90%', height='70%', zoom_start=17)
folium.Circle(location=[13.0556, 80.2837],
              radius=30, # radius in meters
              popup='Marina Beach',
              color='#0000ff', # hexadecimal color code for the blue colour.
              fill=True).add_to(chennai_map)
chennai_map

"""---"""